services:
  api1:
    build: .
    hostname: api1
    environment:
      PORT: 8080
      REFERENCES_PATH: resources/references.json.gz
      NORMALIZATION_PATH: resources/normalization.json
      MCC_RISK_PATH: resources/mcc_risk.json
      GOMAXPROCS: 1
      GOGC: 300
      SEARCH_MODE: ivf
      IVF_CLUSTERS: 1024
      IVF_PROBES: 16
    cpus: 0.25
    mem_limit: 150m

  api2:
    build: .
    hostname: api2
    environment:
      PORT: 8080
      REFERENCES_PATH: resources/references.json.gz
      NORMALIZATION_PATH: resources/normalization.json
      MCC_RISK_PATH: resources/mcc_risk.json
      GOMAXPROCS: 1
      GOGC: 300
      SEARCH_MODE: ivf
      IVF_CLUSTERS: 1024
      IVF_PROBES: 16
    cpus: 0.25
    mem_limit: 150m

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    cpus: 0.5
    mem_limit: 50m
